source/ps.dmv.web/Controllers/DmvController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ps.dmv.common.Core;
using ps.dmv.domain.data.Entities;
using ps.dmv.interfaces.Managers;
using ps.dmv.web.Infrastructure.Core;

namespace ps.dmv.web.Controllers
{
    /// <summary>
    /// DmvController
    /// </summary>
    public partial class DmvController : BaseDmvController
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public virtual ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// DMVs the form.
        /// </summary>
        /// <returns></returns>
        public virtual ActionResult DmvForm()
        {
            return PartialView(MVC.Dmv.Views._dmvCalculationForm);
        }

        /// <summary>
        /// DMVs the form lite.
        /// </summary>
        /// <returns></returns>
        public virtual ActionResult DmvFormLite()
        {
            return PartialView(MVC.Dmv.Views._dmvCalculationFormLite);
        }

        /// <summary>
        /// DMVs the calculation result.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public virtual ActionResult DmvCalculationResult(int id)
        {
            DmvCalculationResult dmvCalculationResult = ServiceLocator.Instance.Resolve<IDmvCalculationManager>().Get(id);

            return PartialView(MVC.Dmv.Views.DmvCalculationResult, dmvCalculationResult);
        }
	}
}

source/ps.dmv.web/Controllers/ExternalImportCarDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.EnterpriseLibrary.Validation;
using ps.dmv.common.Core;
using ps.dmv.common.Exceptions;
using ps.dmv.domain.data.Entities;
using ps.dmv.interfaces.Managers;
using ps.dmv.web.Infrastructure.Core;

namespace ps.dmv.web.Controllers
{
    /// <summary>
    /// ExternalImportCarDataController
    /// </summary>
    public partial class ExternalImportCarDataController : BaseDmvController
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public virtual ActionResult Index()
        {
            ImportMobileDe importMobileDe = new ImportMobileDe();

            return View(importMobileDe);
        }

        /// <summary>
        /// Indexes the specified import mobile de.
        /// </summary>
        /// <param name="importMobileDe">The import mobile de.</param>
        /// <returns></returns>
        [HttpPost]
        public virtual async Task<ActionResult> Index(ImportMobileDe importMobileDe)
        {
            if (!String.IsNullOrEmpty(importMobileDe.Url) && !importMobileDe.Url.Contains("suchen.mobile.de/auto-inserat"))
            {
                this.ModelState.AddModelError("Url", "URL ni iz portala mobile.de");
            }

            if (!this.ModelState.IsValid)
            {
                return View(importMobileDe);
            }

            DmvCalculationResult dmvCalculationResult = null;

            try
            {
                dmvCalculationResult = await ServiceLocator.Instance.Resolve<IMobileDeManager>().ImportCarData(importMobileDe);
            }
            catch (BusinessValidationException businessValidationException)
            {
                this.ModelState.AddModelError(String.Empty, "Napaka pri uvozu. Manjkajoči podatki v avto oglasu. Poizkusite z drugim avto oglasom.");

                foreach (ValidationResult validationResult in businessValidationException.ValidationResultList)
                {
                    this.ModelState.AddModelError(String.Empty, validationResult.Message);//TODO add it into ifra
                }

                return View(importMobileDe);
            }

            return RedirectToAction(MVC.Dmv.DmvCalculationResult(dmvCalculationResult.DmvCalculation.Id));
        }
	}
}

source/ps.dmv.web/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ps.dmv.common.Attributes;
using ps.dmv.common.Core;
using ps.dmv.domain.data.Entities;
using ps.dmv.interfaces.Managers;
using ps.dmv.web.Infrastructure.Core;

namespace ps.dmv.web.Controllers
{
    /// <summary>
    /// StatisticsController
    /// </summary>
    public partial class StatisticsController : BaseDmvController
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public virtual ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Mosts the popular car brand.
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public virtual ActionResult MostPopularCarBrand()
        {
            CarManufacturerNumberStatistics carManufacturerNumberStatistics = ServiceLocator.Instance.Resolve<IStatisticsManager>().GetMostPopularCarBrandStatistics();

            return PartialView(MVC.Statistics.Views._MostPopularCarBrand, carManufacturerNumberStatistics);
        }

        /// <summary>
        /// Calculations the frequency.
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public virtual ActionResult CalculationFrequency()
        {
            CalculationFrequencyStatistics calculationFrequencyStatistics = ServiceLocator.Instance.Resolve<IStatisticsManager>().GetCalculationFrequencyStatistics();

            return PartialView(MVC.Statistics.Views._CalculationFrequency, calculationFrequencyStatistics);
        }
	}
}

source/ps.dmv.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="dmvApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="izračun dmv,dmv,uvoz avtomobila,uvoz avtomobila EU" />
    <link rel="favicon" href="/favicon.ico" />
    <title>DMV Portal - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DMV Portal", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Izračunaj si DMV", "Index", "Dmv")</li>
                    <li>@Html.ActionLink("Uvozi za izračun", "Index", "ExternalImportCarData")</li>
                    <li>@Html.ActionLink("Statistike", "Index", "Statistics")</li>
                    <li>@Html.ActionLink("O Nas", "O-Nas", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Kontakt", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.UtcNow.Year - <a href="@Url.Action(MVC.Home.About())">DMV Portal</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/external")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/application")

    @RenderSection("scripts", required: false)

    <script>
        //(function (i, s, o, g, r, a, m) {
        //    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
        //        (i[r].q = i[r].q || []).push(arguments);
        //    }, i[r].l = 1 * new Date(); a = s.createElement(o),
        //        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m);
        //})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        //ga('create', 'UA-45633433-1', 'azurewebsites.net');
        //ga('send', 'pageview');

        $(function () {

            var cookieScripts = function() {
                // Internal javascript called
                console.log("Running");

                // Loading external javascript file
                $.cookiesDirective.loadScript({
                    uri: 'external.js',
                    appendTo: 'eantics'
                });
            };

            $.cookiesDirective({
                privacyPolicyUri: '/Home/O-Nas',
                explicitConsent: false,
                position: 'bottom',
                scriptWrapper: cookieScripts,
                cookieScripts: 'Google Analytics, Authentication ',
                backgroundColor: '#52B54A',
                linkColor: '#ffffff'
            });
        });
    </script>
    
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments);
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m);
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-45633433-2', 'dmvportal.net');
        ga('send', 'pageview');

    </script>
    
    <!-- AddThis Smart Layers BEGIN -->
    <!-- Go to http://www.addthis.com/get/smart-layers to customize -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5299b1ad2f1f5f59"></script>
    <script type="text/javascript">
        addthis.layers({
            'theme': 'transparent',
            'share': {
                'position': 'left',
                'numPreferredServices': 5
            }
        });
    </script>
    <!-- AddThis Smart Layers END -->

</body>
</html>

source/ps.dmv.web/Views/Shared/_Pager.cshtml
@model List<PagerItem>

<div class="news_post_pager">
    <ul>
        @foreach (PagerItem item in this.Model)
        {
            switch (item.Type)
            {
                case PagerItemType.Page:
                    <li><a href="@item.Url">@item.Title</a></li>
                    break;
                case PagerItemType.SelectedPage:
                    <li class="selected"><span>@item.Title</span></li>
                    break;
                case PagerItemType.Separator:
                    <li class="separator"><span>@item.Title</span></li>
                    break;
                case PagerItemType.Previous:
                    <li class="previous"><a href="@item.Url">@item.Title</a></li>
                    break;
                case PagerItemType.Next:
                    <li class="next"><a href="@item.Url">@item.Title</a></li>
                    break;
            }
        }
    </ul>
</div>

@*<div style="display:inline;">
    @Html.Partial(MVC.Shared.Views._Pager, PagkerItem.GeneratePagerItems(this.Model.TotalPageCount, this.Model.CurrentPageIndex + 1, "?index={0}"))
    @Html.Partial(MVC.Shared.Views._Pager, PagkerItem.GeneratePagerItems(this.Model.TotalPageCount, this.Model.CurrentPageIndex + 1, "?index={0}"))
</div>*@